### PR TITLE
[WIP] Freecad backend

### PR DESCRIPTION
**Pull request by chintal**
I'm working on writing a backend to render gerbers using FreeCAD in 3D (Unpopulated PCB only, not components for now), with the intended use case being ultimate export to STEP/IGES for use in mechanical CAD workflows.

This 'pull request' is intended to be an early preview of the changes I intend to make to the currently existing pcb-tools.gerber codebase. Please let me know if you have any issues with the current approach and/or if you have any notes on how best this could be done to enable ultimate inclusion in pcb-tools.

Actually pulling in these changes may be somewhat counter-productive as is right now. If you would like to pull in some of the changes (such as the layer dialect code), let me know and I'll figure out how to make a cleaner pull request with only that.

### CODE REVIEW

**Comment by phsilva** [comment]
@chintal, very nice idea.

I will definitely get the layer guessing code first,I already have some on my own to merge that can detect most formats I found.

Look forward to see any STEP/IGES examples.

**Comment by chintal** [comment]
The changes for layer guessing and other similar refactoring are available now. Though the freecad bits aren't yet there, the current state of the code should be merge-able without (hopefully) breaking anything.

**Comment by chintal** [comment]
Render example : 

http://static.chintal.in/~chintal/pcb-tools-freecad/

**Comment by phsilva** [comment]
Fantastic job @chintal. I will try to get some Blender render from it as well to see how realistic we can get.

**Comment by chintal** [comment]
Closing this PR. Will perhaps get back to it at some point.

**Pull request closed without merging**
