### PR TITLE
Add aperture macro parsing and evaluation.

### PR DESCRIPTION
**Pull request by phsilva**
Aperture macros can get complex with arithmetical operations,
variables and variables substitution.

Current pcb-tools code just read each macro block as an independent
unit, this cannot deal with variables that get changed after used.

This patch splits the task in two: first we parse all macro content
and creates a bytecode representation of all operations. This bytecode
representation will be executed when an AD command is issues passing
the required parameters.

Parsing is heavily based on gerbv using a Shunting Yard approach to
math parsing.

Integration with rs274x.py code is not finished as I need to figure out
how to integrate the final macro primitives with the graphical primitives
already in use.

### CODE REVIEW

**Comment by phsilva** [comment]
Testing and final integration still needed, but appreciate a check on the general approach.

**Comment by hamiltonkibbe** [comment]
I haven't gotten a chance to look over this yet, but I'll take a look this evening

**Comment by phsilva** [comment]
Yes, I was looking at primitives.py and do think it is complete. Only missing part is that all the AM*Primitive classes should create the equivalent graphical primitives to be rendered.

**Comment by hamiltonkibbe** [comment]
The approach looks good. Could you just take a look and see why those 3 tests fail with this update. Ultimately we'll need to add a bunch of test cases that cover the aperture macro variables, but for now I'd just like to make sure that an aperture macro with no variables still works.

Hamilton

**Comment by phsilva** [comment]
Tests passing again.

**Comment by hamiltonkibbe** [comment]
Looks awesome.

**Pull request merged**
