### PR TITLE
Add support for latest Python releases

### PR DESCRIPTION
**Pull request by johnthagen**
Add support in CI for latest supported Python versions 3.6, 3.7, and 3.8.

### CODE REVIEW

**Comment by johnthagen** [comment]
Python 3.7+ failure:

```
ERROR: Test file type detection
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/curtacircuitos/pcb-tools/gerber/excellon_statements.py", line 978, in pairwise
    yield tuple([next(itr) for i in range(2)])
  File "/home/travis/build/curtacircuitos/pcb-tools/gerber/excellon_statements.py", line 978, in <listcomp>
    yield tuple([next(itr) for i in range(2)])
StopIteration
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/curtacircuitos/pcb-tools/gerber/tests/test_excellon.py", line 23, in test_format_detection
    settings = detect_excellon_format(data)
  File "/home/travis/build/curtacircuitos/pcb-tools/gerber/excellon.py", line 826, in detect_excellon_format
    p.parse_raw(data)
  File "/home/travis/build/curtacircuitos/pcb-tools/gerber/excellon.py", line 435, in parse_raw
    self._parse_line(line.strip())
  File "/home/travis/build/curtacircuitos/pcb-tools/gerber/excellon.py", line 639, in _parse_line
    tool = ExcellonTool.from_excellon(line, self._settings(), None, self.plated)
  File "/home/travis/build/curtacircuitos/pcb-tools/gerber/excellon_statements.py", line 155, in from_excellon
    commands = [(command, value) for command, value in pairwise(commands)]
  File "/home/travis/build/curtacircuitos/pcb-tools/gerber/excellon_statements.py", line 155, in <listcomp>
    commands = [(command, value) for command, value in pairwise(commands)]
RuntimeError: generator raised StopIteration
```

Perhaps fixed by #104?

**Comment by MarinMikael** [comment]
Hello,
> Perhaps fixed by #104?
Yes. 

However, I am not sure if this package is still maintained.

**Comment by phsilva** [comment]
Hi @MarinMikael, I left `pcb-tools` for a while but I am back maintaining it. Will take a look at it now.

**Comment by phsilva** [comment]
Merged #104 but tests still fail for `3.8`, looks related to coverage package version. Think we should split this in two, first get 3.7 in and later update packages and tests for 3.8, what do you think?

**Comment by MarinMikael** [comment]
Hello,
Welcome back. :D 

pcb-tools uses coverage 3.7.1, which was released in 2013. This specific line was removed, upgrading the package's version in [test-requirements.txt](../blob/master/test-requirements.txt) should be enough, if it doesn't break anything else.

**Comment by MarinMikael** [comment]
I confirm that #104 merged with #105 and modifying coverage to 4.5.4 passes the Travis CI test in my master branch.

**Comment by phsilva** [comment]
I've upgrade the dependencies, CI passing now. Will merge. Thanks @MarinMikael and @johnthagen .

**Pull request merged**
