### PR TITLE
Add fix to work with excellon with no tool definition.

### PR DESCRIPTION
**Pull request by phsilva**
I found out that Proteus generate some strange Excellon without any tool definition.
Gerbv renders it correctly and after digging in I found the heuristic that they use
to "guess" the tool diameter. This change replicates this behavior on pcb-tools.

### CODE REVIEW

**Comment by phsilva** [comment]
@hamiltonkibbe, any better idea about how to handle this? otherwise I'l merge it as is.

**Comment by phsilva** [comment]
(random thought) Think that the way we write files now will have to change. Originally pcb-tools was meant as a statement oriented thing but we need to move upper in the structure and think about the features/primitives itself and even our writers should take this into account. Not simply mirror what is in the original file, but write the way we think is write, keeping the same "functionally" as in the original file.

**Comment by hamiltonkibbe** [comment]
I don't see any issues,  Is this just a proteus thing?  ```16 + 8 * $TOOL_NUMBER``` seems like it comes from somewhere... maybe they just backed it out of some proteus-generated files? either way, if it works I'm fine with it.

I agree with you that the writers should generate files from the primitives and not the statements. The Excellon writer does that as of 94f3976915d64a77135a1fdc8983085ee8d2e1f9. It will be a bit more complicated for gerber files but I think that's the right direction.

**Comment by phsilva** [comment]
Found nothing on gerbv commit related to where this came from, but they say it is "probably not what you want". I found out that for some boards I have this actually works.

Excellon writer still uses the header verbatim from the file, that's why I had to hack it to insert the new ExcellonTool somewhere inside the "header". It should create the header from FileSettings and tolls from self.tools to make this complete. But we are getting there.

In addition, Gerber and Excellon would be able to share some code as both files are in fact representing same sort of primitives (excellon adds lots of metadata to drills but this is just metadata and most fabs simply ignore it when it pass through the processing pipeline, feed rates and so on). I will hack something to convert between Gerber and Excellon as I am starting to get more Gerbers files for drills and my current pipeline makes the distinction between those two.

**Pull request merged**
